// ÜRETİLMİŞ DOSYA — scripts/pin-ikonlari.mjs (#59 B). Elle düzenleme; ikon/renk değişince betiği çalıştır.
import type { ImageRequireSource } from 'react-native';

/** "<ikon>-<rrggbb>" → paketlenmiş PNG (@1x/@2x/@3x). */
export const PIN_IKONLARI: Record<string, ImageRequireSource> = {
  'kamera-3b6fe0': require('../../../assets/pin/kamera-3b6fe0.png'),
  'muze-8a4fd6': require('../../../assets/pin/muze-8a4fd6.png'),
  'ibadet-6b7280': require('../../../assets/pin/ibadet-6b7280.png'),
  'catal-e8590c': require('../../../assets/pin/catal-e8590c.png'),
  'fincan-9a5b2e': require('../../../assets/pin/fincan-9a5b2e.png'),
  'agac-1f8a4c': require('../../../assets/pin/agac-1f8a4c.png'),
  'dag-0ea5e9': require('../../../assets/pin/dag-0ea5e9.png'),
  'canta-c2185b': require('../../../assets/pin/canta-c2185b.png'),
  'kamera-ffffff': require('../../../assets/pin/kamera-ffffff.png'),
  'muze-ffffff': require('../../../assets/pin/muze-ffffff.png'),
  'ibadet-ffffff': require('../../../assets/pin/ibadet-ffffff.png'),
  'catal-ffffff': require('../../../assets/pin/catal-ffffff.png'),
  'fincan-ffffff': require('../../../assets/pin/fincan-ffffff.png'),
  'agac-ffffff': require('../../../assets/pin/agac-ffffff.png'),
  'dag-ffffff': require('../../../assets/pin/dag-ffffff.png'),
  'canta-ffffff': require('../../../assets/pin/canta-ffffff.png'),
  'tik-ffffff': require('../../../assets/pin/tik-ffffff.png'),
  'ev-ffffff': require('../../../assets/pin/ev-ffffff.png'),
  'araba-1f4fc2': require('../../../assets/pin/araba-1f4fc2.png'),
  'araba-cf5a22': require('../../../assets/pin/araba-cf5a22.png'),
  'araba-0b7d5d': require('../../../assets/pin/araba-0b7d5d.png'),
  'araba-6e3fab': require('../../../assets/pin/araba-6e3fab.png'),
  'araba-b83762': require('../../../assets/pin/araba-b83762.png'),
  'araba-0b84ba': require('../../../assets/pin/araba-0b84ba.png'),
  'ok-ffffff': require('../../../assets/pin/ok-ffffff.png'),
  'daire-kamera-28': require('../../../assets/pin/daire-kamera-28.png'),
  'kucuk-kamera-20': require('../../../assets/pin/kucuk-kamera-20.png'),
  'dolu-kamera-28': require('../../../assets/pin/dolu-kamera-28.png'),
  'igne-daire-kamera': require('../../../assets/pin/igne-daire-kamera.png'),
  'igne-dolu-kamera': require('../../../assets/pin/igne-dolu-kamera.png'),
  'one-daire-kamera-28': require('../../../assets/pin/one-daire-kamera-28.png'),
  'one-dolu-kamera-28': require('../../../assets/pin/one-dolu-kamera-28.png'),
  'igne-one-daire-kamera': require('../../../assets/pin/igne-one-daire-kamera.png'),
  'igne-one-dolu-kamera': require('../../../assets/pin/igne-one-dolu-kamera.png'),
  'daire-muze-28': require('../../../assets/pin/daire-muze-28.png'),
  'kucuk-muze-20': require('../../../assets/pin/kucuk-muze-20.png'),
  'dolu-muze-28': require('../../../assets/pin/dolu-muze-28.png'),
  'igne-daire-muze': require('../../../assets/pin/igne-daire-muze.png'),
  'igne-dolu-muze': require('../../../assets/pin/igne-dolu-muze.png'),
  'one-daire-muze-28': require('../../../assets/pin/one-daire-muze-28.png'),
  'one-dolu-muze-28': require('../../../assets/pin/one-dolu-muze-28.png'),
  'igne-one-daire-muze': require('../../../assets/pin/igne-one-daire-muze.png'),
  'igne-one-dolu-muze': require('../../../assets/pin/igne-one-dolu-muze.png'),
  'daire-ibadet-28': require('../../../assets/pin/daire-ibadet-28.png'),
  'kucuk-ibadet-20': require('../../../assets/pin/kucuk-ibadet-20.png'),
  'dolu-ibadet-28': require('../../../assets/pin/dolu-ibadet-28.png'),
  'igne-daire-ibadet': require('../../../assets/pin/igne-daire-ibadet.png'),
  'igne-dolu-ibadet': require('../../../assets/pin/igne-dolu-ibadet.png'),
  'one-daire-ibadet-28': require('../../../assets/pin/one-daire-ibadet-28.png'),
  'one-dolu-ibadet-28': require('../../../assets/pin/one-dolu-ibadet-28.png'),
  'igne-one-daire-ibadet': require('../../../assets/pin/igne-one-daire-ibadet.png'),
  'igne-one-dolu-ibadet': require('../../../assets/pin/igne-one-dolu-ibadet.png'),
  'daire-catal-28': require('../../../assets/pin/daire-catal-28.png'),
  'kucuk-catal-20': require('../../../assets/pin/kucuk-catal-20.png'),
  'dolu-catal-28': require('../../../assets/pin/dolu-catal-28.png'),
  'igne-daire-catal': require('../../../assets/pin/igne-daire-catal.png'),
  'igne-dolu-catal': require('../../../assets/pin/igne-dolu-catal.png'),
  'one-daire-catal-28': require('../../../assets/pin/one-daire-catal-28.png'),
  'one-dolu-catal-28': require('../../../assets/pin/one-dolu-catal-28.png'),
  'igne-one-daire-catal': require('../../../assets/pin/igne-one-daire-catal.png'),
  'igne-one-dolu-catal': require('../../../assets/pin/igne-one-dolu-catal.png'),
  'daire-fincan-28': require('../../../assets/pin/daire-fincan-28.png'),
  'kucuk-fincan-20': require('../../../assets/pin/kucuk-fincan-20.png'),
  'dolu-fincan-28': require('../../../assets/pin/dolu-fincan-28.png'),
  'igne-daire-fincan': require('../../../assets/pin/igne-daire-fincan.png'),
  'igne-dolu-fincan': require('../../../assets/pin/igne-dolu-fincan.png'),
  'one-daire-fincan-28': require('../../../assets/pin/one-daire-fincan-28.png'),
  'one-dolu-fincan-28': require('../../../assets/pin/one-dolu-fincan-28.png'),
  'igne-one-daire-fincan': require('../../../assets/pin/igne-one-daire-fincan.png'),
  'igne-one-dolu-fincan': require('../../../assets/pin/igne-one-dolu-fincan.png'),
  'daire-agac-28': require('../../../assets/pin/daire-agac-28.png'),
  'kucuk-agac-20': require('../../../assets/pin/kucuk-agac-20.png'),
  'dolu-agac-28': require('../../../assets/pin/dolu-agac-28.png'),
  'igne-daire-agac': require('../../../assets/pin/igne-daire-agac.png'),
  'igne-dolu-agac': require('../../../assets/pin/igne-dolu-agac.png'),
  'one-daire-agac-28': require('../../../assets/pin/one-daire-agac-28.png'),
  'one-dolu-agac-28': require('../../../assets/pin/one-dolu-agac-28.png'),
  'igne-one-daire-agac': require('../../../assets/pin/igne-one-daire-agac.png'),
  'igne-one-dolu-agac': require('../../../assets/pin/igne-one-dolu-agac.png'),
  'daire-dag-28': require('../../../assets/pin/daire-dag-28.png'),
  'kucuk-dag-20': require('../../../assets/pin/kucuk-dag-20.png'),
  'dolu-dag-28': require('../../../assets/pin/dolu-dag-28.png'),
  'igne-daire-dag': require('../../../assets/pin/igne-daire-dag.png'),
  'igne-dolu-dag': require('../../../assets/pin/igne-dolu-dag.png'),
  'one-daire-dag-28': require('../../../assets/pin/one-daire-dag-28.png'),
  'one-dolu-dag-28': require('../../../assets/pin/one-dolu-dag-28.png'),
  'igne-one-daire-dag': require('../../../assets/pin/igne-one-daire-dag.png'),
  'igne-one-dolu-dag': require('../../../assets/pin/igne-one-dolu-dag.png'),
  'daire-canta-28': require('../../../assets/pin/daire-canta-28.png'),
  'kucuk-canta-20': require('../../../assets/pin/kucuk-canta-20.png'),
  'dolu-canta-28': require('../../../assets/pin/dolu-canta-28.png'),
  'igne-daire-canta': require('../../../assets/pin/igne-daire-canta.png'),
  'igne-dolu-canta': require('../../../assets/pin/igne-dolu-canta.png'),
  'one-daire-canta-28': require('../../../assets/pin/one-daire-canta-28.png'),
  'one-dolu-canta-28': require('../../../assets/pin/one-dolu-canta-28.png'),
  'igne-one-daire-canta': require('../../../assets/pin/igne-one-daire-canta.png'),
  'igne-one-dolu-canta': require('../../../assets/pin/igne-one-dolu-canta.png'),
  'tik-28': require('../../../assets/pin/tik-28.png'),
  'tamam-28': require('../../../assets/pin/tamam-28.png'),
  'igne-tik': require('../../../assets/pin/igne-tik.png'),
  'igne-tamam': require('../../../assets/pin/igne-tamam.png'),
  'otel-28': require('../../../assets/pin/otel-28.png'),
};

/** "<ikon>-<rrggbb>" anahtarı. */
export function pinIkonuAnahtari(ikon: string, renk: string): string {
  return `${ikon}-${renk.replace('#', '').toLowerCase()}`;
}

/** #65: iğne (seçili) görselinin çapası — PNG içinde ucun konumu (kenar payı dahil). */
export const IGNE_CAPA = { x: 0.5, y: 0.875 } as const;

/** Pin içi ikonun PNG'si; üretilmemiş (ikon, renk) çifti için undefined → SVG'ye düşülür. */
export function pinIkonuPng(ikon: string, renk: string): ImageRequireSource | undefined {
  return PIN_IKONLARI[pinIkonuAnahtari(ikon, renk)];
}
